image: nixos/nix:latest

before_script:
- export LC_ALL=C.UTF-8
- nix-env -iA nixpkgs.stack
- nix-env -iA nixpkgs.git
- nix-env -iA nixpkgs.hlint

stages:
- lint
- build
- test

lint:
  stage: lint
  script:
  - hlint . --ignore-glob=test/Spec.hs

build:
  stage: build
  script:
  - stack --nix build --ghc-options "-Wall -Werror"

test:
  stage: test
  script:
  - stack --nix test --ghc-options "-Wall -Werror"
