image: nixos/nix:latest

before_script:
- export LC_ALL=C.UTF-8
- nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
- nix-channel --update
- nix-env -iA nixpkgs.stack
- nix-env -iA nixpkgs.git
- nix-env -iA nixpkgs.cacert
- nix-env -iA nixpkgs.hlint
- nix-env -iA nixpkgs.cachix
- cachix use iohk
- cachix use shakebook

stages:
- lint
- build
- test

lint:
  stage: lint
  script:
  - hlint . --ignore-glob=test/Spec.hs

build:
  stage: build
  script:
  - nix-build nix/default.nix -A shakebook

test:
  stage: test
  script:
  - nix-build nix/default.nix -A shakebook.components.tests
