image: lnl7/nix-docker:latest

before_script:
- export LC_ALL=C.UTF-8
- nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
- nix-channel --update
- nix-env -iA nixpkgs.cachix
- nix-env -iA nixpkgs.openssh
- cachix use iohk
- cachix use shakebook
- pwd
- echo "$NIXBUILD_SSH_KEY" > /root/nixbuild.key
- mkdir -p /etc/ssh/
- echo "Host eu.nixbuild.net
  PubkeyAcceptedKeyTypes ssh-ed25519
  IdentityFile /root/nixbuild.key"
  >> /etc/ssh/ssh_config


stages:
- build
- cache


build:
  stage: build
  script:
    - nix-build -A shakebook -K --builders "ssh://eu.nixbuild.net x86_64-linux - 100 1 big-parallel,benchmark"

cachix:
  stage: cache
  script:
  - nix-store -qR --include-outputs $(nix-store -q --deriver $(nix-build -A shakebook -K)) | cachix push shakebook
