image: nixos/nix:latest

before_script:
- export LC_ALL=C.UTF-8
- nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
- nix-channel --update
- nix-env -iA nixpkgs.stack
- nix-env -iA nixpkgs.git
- nix-env -iA nixpkgs.cacert
- nix-env -iA nixpkgs.hlint
- nix-env -iA nixpkgs.cachix
- cachix use iohk
- cachix use shakebook

stages:
- lint
- build
- cache

lint:
  stage: lint
  script:
  - hlint . --ignore-glob=test/Spec.hs

build:
  stage: build
  script:
  - nix-build -A shakebook -K

cachix:
  stage: cache
  script:
  - nix-store -qR --include-outputs $(nix-store -q --deriver $(nix-build -A shakebook -K)) | cachix push shakebook
