name:                shakebook
version:             0.7.1.0
license:             MIT
category:            Web
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Shake-based technical documentation generator; HTML & PDF
description: >
   Shakebook is a documentation generator aimed at covering all the bases for
   mathematical, technical and scientific diagrams and typesetting. Shakebook
   provides combinators for taking markdown files and combining them into
   documents, but allowing the user to control how. Shakebook provides general
   combinators for templating single pages, cofree comonads for representing
   tables of contents, and zipper comonads for representing pagers.

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  shakebook-test:
    main:             Spec.hs
    source-dirs:      test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shakebook
    - tasty
    - tasty-golden

dependencies:
- aeson >= 1.5.2.0
- aeson-with >= 0.1.1.0
- base >= 4.7 && < 5
- comonad
- comonad-extras
- doctemplates
- feed
- free
- ixset-typed
- lens
- lens-aeson
- mustache
- rio
- pandoc >= 2.9.2.1
- pandoc-types
- path-extensions >= 0.0.1.0
- shake-plus >= 0.1.7.0
- slick >= 1.0.1.1
- split
- text-time
- zipper-extra >= 0.1.3.0
