name:                shakebook
version:             0.1.5.1
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firt@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Shake-based technical documentation generator.
category:            Web

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  shakebook-simple-blog:
    main:             Main.hs
    source-dirs:      app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - shakebook

tests:
  shakebook-test:
    main:             Spec.hs
    source-dirs:      test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shakebook
    - tasty
    - tasty-golden

dependencies:
- aeson
- base >= 4.7 && < 5
- comonad
- comonad-extras
- doctemplates
- extra
- feed
- free
- lens
- lens-aeson
- relude
- rio
- pandoc
- pandoc-types
- shake
- slick
- split
- text-time
