resolver: nightly-2020-09-19
packages:
- .
extra-deps:
- commonmark-0.1.0.2
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.0
- compdoc-0.1.0.0
- composite-aeson-cofree-list-0.1.0.0
- composite-aeson-throw-0.1.0.0
- composite-aeson-writeonly-0.1.0.0
- pandoc-2.10.1
- pandoc-throw-0.1.0.0
- path-utils-0.1.0.0
- shake-plus-extended-0.4.1.0
- slick-1.0.1.1
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
