resolver: nightly-2020-07-08
packages:
- .
extra-deps:
- git: https://github.com/locallycompact/composite
  commit: 0c7226cb65e0bdbba39ed812c0d992aa1fad3756
  subdirs:
  - composite-aeson
  - composite-base
- comonad-extras-4.0.1
- hslua-1.1.2
- ixset-typed-conversions-0.1.0.0
- lucid-cdn-0.1.1.0
- jira-wiki-markup-1.3.2
- pandoc-2.10
- slick-1.0.1.1
- text-time-0.2.0
- vinyl-0.13.0
- zipper-extra-0.1.3.0
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
