resolver: nightly-2020-07-06
packages:
- .
extra-deps:
- aeson-1.5.2.0
- comonad-extras-4.0.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- pandoc-2.10
- shake-plus-0.2.0.0
- slick-1.0.1.1
- text-time-0.2.0
- within-0.2.0.0
- zipper-extra-0.1.3.0
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
