resolver: lts-16.5
packages:
- .
extra-deps:
- aeson-with-0.1.1.1
- binary-instances-1.0.0.1
- git: https://github.com/locallycompact/composite
  commit: c489119a911969c2eeed84e916a2fb92f9a34d3b
  subdirs:
  - composite-aeson
  - composite-base
- comonad-extras-4.0.1
- ixset-typed-conversions-0.1.0.0
- lucid-cdn-0.1.1.0
- path-extensions-0.1.1.0
- path-like-0.2.0.1
- shake-plus-0.2.0.0
- slick-1.0.1.1
- text-time-0.2.0
- vinyl-0.13.0
- within-0.2.0.0
- zipper-extra-0.1.3.0
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
