resolver: lts-16.2
packages:
- .
extra-deps:
- aeson-with-0.1.1.0
- comonad-extras-4.0.1
- path-extensions-0.1.0.1
- slick-1.0.1.1
- text-time-0.2.0
- zipper-extra-0.1.3.0
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
