resolver: nightly-2020-08-30
packages:
- .
extra-deps:
- commonmark-0.1.0.2
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.0
- pandoc-2.10.1
- slick-1.0.1.1
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
