resolver: nightly-2020-06-22
packages:
- .
extra-deps:
- aeson-1.5.2.0
- aeson-with-0.1.0.2
- base-noprelude-4.13.0.0
- comonad-extras-4.0.1
- haddock-library-1.8.0
- ixset-1.1.1.1
- pandoc-2.9.2.1
- path-extensions-0.1.0.1
- slick-1.0.1.1
- syb-with-class-0.6.1.13
- text-time-0.2.0
- zipper-extra-0.1.2.1
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
