resolver: nightly-2020-08-01
packages:
- .
extra-deps:
- composite-aeson-0.7.3.0
- composite-base-0.7.3.0
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- pandoc-2.10
- slick-1.0.1.1
- text-time-0.2.0
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
