resolver: nightly-2020-08-14
packages:
- .
extra-deps:
- git: https://github.com/locallycompact/composite
  commit: a3e11e5e8d97eb5b42b645c8e66905c9c1024e03
  subdirs:
  - composite-aeson
  - composite-base
  - composite-aeson-path
  - composite-binary-instance
  - composite-hashable-instance
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- pandoc-2.10
- slick-1.0.1.1
- text-time-0.2.0
allow-newer: true
nix:
  enable: false
  packages: [zlib]
ghc-options:
  "$locals": -fwrite-ide-info
